version = 0.1

[default.global.parameters]
stack_name = "ttleague-players"

[default.build.parameters]
cached = true
parallel = true

[dev.build.parameters]
parameter_overrides = "Environment=dev LambdaArchitecture=arm64 DotnetBuildConfiguration=Debug DomainName= "

[dev.local_start_api.parameters]
parameter_overrides = "Environment=dev LambdaArchitecture=arm64 DotnetBuildConfiguration=Debug DomainName= "

[test.build.parameters]
parameter_overrides = "Environment=test LambdaArchitecture=arm64 DotnetBuildConfiguration=Release DomainName= "

[test.local_start_api.parameters]
parameter_overrides = "Environment=test LambdaArchitecture=arm64 DotnetBuildConfiguration=Release DomainName= "

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false

[dev.deploy.parameters]
parameter_overrides = "Environment=dev LambdaArchitecture=arm64 DotnetBuildConfiguration=Debug DomainName= "
stack_name = "ttleague-players-dev"

[test.deploy.parameters]
parameter_overrides = "Environment=test LambdaArchitecture=arm64 DotnetBuildConfiguration=Release DomainName= "
stack_name = "ttleague-players-test"

[staging.deploy.parameters]
parameter_overrides = "Environment=staging LambdaArchitecture=x86_64 DotnetBuildConfiguration=Release DomainName=staging.yourdomain.com"
stack_name = "ttleague-players-staging"
region = "us-east-1"

[prod.deploy.parameters]
parameter_overrides = "Environment=prod LambdaArchitecture=x86_64 DotnetBuildConfiguration=Release DomainName=yourdomain.com"
stack_name = "ttleague-players-prod"
region = "us-east-1"