version = 0.1

[default.global.parameters]
stack_name = "ttleague-players"

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = false
fail_on_empty_changeset = false

[dev.deploy.parameters]
parameter_overrides = "Environment=dev DomainName="
stack_name = "ttleague-players-dev"

[test.deploy.parameters]
parameter_overrides = "Environment=test DomainName="
stack_name = "ttleague-players-test"

[staging.deploy.parameters]
parameter_overrides = "Environment=staging DomainName=staging.yourdomain.com"
stack_name = "ttleague-players-staging"
region = "us-east-1"

[prod.deploy.parameters]
parameter_overrides = "Environment=prod DomainName=yourdomain.com"
stack_name = "ttleague-players-prod"
region = "us-east-1"